"""
Static knowledge base used to enrich raw CNN predictions with actionable
advice. Mirrors the PlantVillage class names so it works directly once you
plug in a model trained on that dataset. Extend/edit freely, or manage this
data live via the Admin Panel (see routers/admin_routes.py), which reads
from the `diseases` DB table seeded from this file.
"""

DISEASE_CLASSES = [
    "Tomato___Healthy",
    "Tomato___Early_Blight",
    "Tomato___Late_Blight",
    "Tomato___Leaf_Mold",
    "Tomato___Septoria_Leaf_Spot",
    "Potato___Healthy",
    "Potato___Early_Blight",
    "Potato___Late_Blight",
    "Corn___Healthy",
    "Corn___Common_Rust",
    "Corn___Northern_Leaf_Blight",
    "Grape___Healthy",
    "Grape___Black_Rot",
    "Apple___Healthy",
    "Apple___Scab",
    "Apple___Black_Rot",
]

DISEASE_INFO = {
    "Tomato___Healthy": {
        "crop": "Tomato", "severity": "Low",
        "treatment": "No treatment needed. Plant is healthy.",
        "fertilizer": "Continue balanced NPK (10-10-10) feeding every 3-4 weeks.",
        "prevention": "Maintain good spacing, water at the base, and monitor weekly.",
        "name_mr": "टोमॅटो - निरोगी",
        "treatment_mr": "कोणत्याही उपचाराची गरज नाही. रोपटे निरोगी आहे.",
        "fertilizer_mr": "दर ३-४ आठवड्यांनी संतुलित NPK (10-10-10) खत द्या.",
        "prevention_mr": "योग्य अंतर राखा, मुळाशी पाणी द्या आणि दर आठवड्याला तपासणी करा.",
    },
    "Tomato___Early_Blight": {
        "crop": "Tomato", "severity": "Medium",
        "treatment": "Apply chlorothalonil or copper-based fungicide every 7-10 days. Remove infected lower leaves.",
        "fertilizer": "Use potassium-rich fertilizer (e.g., 5-10-10) to strengthen plant resistance.",
        "prevention": "Rotate crops yearly, avoid overhead watering, mulch soil to prevent spore splash.",
        "name_mr": "टोमॅटो - लवकर करपा (अर्ली ब्लाइट)",
        "treatment_mr": "क्लोरोथॅलोनिल किंवा कॉपर-आधारित बुरशीनाशक दर ७-१० दिवसांनी फवारा. खालची संक्रमित पाने काढून टाका.",
        "fertilizer_mr": "रोपाची प्रतिकारशक्ती वाढवण्यासाठी पोटॅशियमयुक्त खत (उदा. 5-10-10) वापरा.",
        "prevention_mr": "दरवर्षी पीक फेरपालट करा, वरून पाणी देणे टाळा, बुरशीचे तुषार थांबवण्यासाठी मातीवर आच्छादन (मल्चिंग) करा.",
    },
    "Tomato___Late_Blight": {
        "crop": "Tomato", "severity": "High",
        "treatment": "Apply fungicides containing mancozeb or metalaxyl immediately. Destroy heavily infected plants.",
        "fertilizer": "Avoid excess nitrogen; use balanced fertilizer to avoid lush growth that favors disease.",
        "prevention": "Ensure good air circulation, avoid wet foliage, use resistant varieties.",
        "name_mr": "टोमॅटो - उशीरा करपा (लेट ब्लाइट)",
        "treatment_mr": "मॅन्कोझेब किंवा मेटालॅक्सिल असलेले बुरशीनाशक ताबडतोब फवारा. जास्त संक्रमित रोपे नष्ट करा.",
        "fertilizer_mr": "जास्त नत्र (नायट्रोजन) टाळा; रोगाला प्रोत्साहन देणाऱ्या जास्त वाढीपासून बचावासाठी संतुलित खत वापरा.",
        "prevention_mr": "चांगली हवा खेळती राहील याची काळजी घ्या, पाने ओली राहणे टाळा, प्रतिकारक जाती वापरा.",
    },
    "Tomato___Leaf_Mold": {
        "crop": "Tomato", "severity": "Medium",
        "treatment": "Apply copper fungicide, improve ventilation in greenhouse/field.",
        "fertilizer": "Balanced NPK feed; avoid excess nitrogen.",
        "prevention": "Reduce humidity, avoid leaf wetness, space plants properly.",
        "name_mr": "टोमॅटो - पानावरील बुरशी (लीफ मोल्ड)",
        "treatment_mr": "कॉपर बुरशीनाशक फवारा, हरितगृह/शेतातील हवा खेळती ठेवा.",
        "fertilizer_mr": "संतुलित NPK खत; जास्त नत्र टाळा.",
        "prevention_mr": "आर्द्रता कमी करा, पाने ओली राहणे टाळा, रोपांमध्ये योग्य अंतर ठेवा.",
    },
    "Tomato___Septoria_Leaf_Spot": {
        "crop": "Tomato", "severity": "Medium",
        "treatment": "Remove infected leaves and apply chlorothalonil-based fungicide.",
        "fertilizer": "Balanced 10-10-10 fertilizer to maintain plant vigor.",
        "prevention": "Mulch, avoid overhead irrigation, rotate crops every season.",
        "name_mr": "टोमॅटो - सेप्टोरिया पानावरील ठिपके",
        "treatment_mr": "संक्रमित पाने काढून टाका आणि क्लोरोथॅलोनिल-आधारित बुरशीनाशक फवारा.",
        "fertilizer_mr": "रोपाची तंदुरुस्ती राखण्यासाठी संतुलित 10-10-10 खत.",
        "prevention_mr": "मल्चिंग करा, वरून पाणी देणे टाळा, दरवर्षी पीक फेरपालट करा.",
    },
    "Potato___Healthy": {
        "crop": "Potato", "severity": "Low",
        "treatment": "No treatment needed.",
        "fertilizer": "Balanced NPK with extra potassium for tuber development.",
        "prevention": "Regular field monitoring and proper drainage.",
        "name_mr": "बटाटा - निरोगी",
        "treatment_mr": "कोणत्याही उपचाराची गरज नाही.",
        "fertilizer_mr": "कंद वाढीसाठी जास्त पोटॅशियमसह संतुलित NPK खत.",
        "prevention_mr": "नियमित शेत तपासणी आणि योग्य निचरा.",
    },
    "Potato___Early_Blight": {
        "crop": "Potato", "severity": "Medium",
        "treatment": "Apply mancozeb or chlorothalonil fungicide at first sign of spots.",
        "fertilizer": "Avoid excess nitrogen; use balanced fertilizer with adequate potassium.",
        "prevention": "Rotate crops, remove plant debris, avoid overhead irrigation.",
        "name_mr": "बटाटा - लवकर करपा",
        "treatment_mr": "ठिपके दिसताच मॅन्कोझेब किंवा क्लोरोथॅलोनिल बुरशीनाशक फवारा.",
        "fertilizer_mr": "जास्त नत्र टाळा; पुरेशा पोटॅशियमसह संतुलित खत वापरा.",
        "prevention_mr": "पीक फेरपालट करा, पिकांचे अवशेष काढून टाका, वरून पाणी देणे टाळा.",
    },
    "Potato___Late_Blight": {
        "crop": "Potato", "severity": "High",
        "treatment": "Apply systemic fungicide (metalaxyl) immediately; destroy severely infected plants.",
        "fertilizer": "Balanced fertilization; avoid excess nitrogen which promotes soft growth.",
        "prevention": "Use certified disease-free seed tubers, ensure good drainage and airflow.",
        "name_mr": "बटाटा - उशीरा करपा",
        "treatment_mr": "ताबडतोब प्रणालीगत बुरशीनाशक (मेटालॅक्सिल) फवारा; तीव्र संक्रमित रोपे नष्ट करा.",
        "fertilizer_mr": "संतुलित खत द्या; मऊ वाढ टाळण्यासाठी जास्त नत्र टाळा.",
        "prevention_mr": "प्रमाणित रोगमुक्त बियाणे कंद वापरा, चांगला निचरा आणि हवा खेळती राहील याची खात्री करा.",
    },
    "Corn___Healthy": {
        "crop": "Corn", "severity": "Low",
        "treatment": "No treatment needed.",
        "fertilizer": "Standard nitrogen-based fertilizer schedule.",
        "prevention": "Routine scouting and crop rotation.",
        "name_mr": "मका - निरोगी",
        "treatment_mr": "कोणत्याही उपचाराची गरज नाही.",
        "fertilizer_mr": "नियमित नत्र-आधारित खत वेळापत्रक पाळा.",
        "prevention_mr": "नियमित पाहणी आणि पीक फेरपालट करा.",
    },
    "Corn___Common_Rust": {
        "crop": "Corn", "severity": "Medium",
        "treatment": "Apply triazole or strobilurin fungicide if severe.",
        "fertilizer": "Ensure adequate potassium to boost plant immunity.",
        "prevention": "Plant resistant hybrids, avoid dense planting.",
        "name_mr": "मका - सामान्य तांबेरा (रस्ट)",
        "treatment_mr": "तीव्रता जास्त असल्यास ट्रायझोल किंवा स्ट्रोबिल्युरिन बुरशीनाशक फवारा.",
        "fertilizer_mr": "रोपाची प्रतिकारशक्ती वाढवण्यासाठी पुरेसे पोटॅशियम द्या.",
        "prevention_mr": "प्रतिकारक संकरित जाती लावा, दाट लागवड टाळा.",
    },
    "Corn___Northern_Leaf_Blight": {
        "crop": "Corn", "severity": "Medium",
        "treatment": "Apply foliar fungicide at early lesion stage.",
        "fertilizer": "Balanced NPK; avoid nitrogen excess.",
        "prevention": "Crop rotation, resistant hybrids, residue management.",
        "name_mr": "मका - उत्तर पानावरील करपा",
        "treatment_mr": "सुरुवातीच्या टप्प्यात पानांवरील बुरशीनाशक फवारा.",
        "fertilizer_mr": "संतुलित NPK खत; जास्त नत्र टाळा.",
        "prevention_mr": "पीक फेरपालट, प्रतिकारक संकरित जाती, पिकांच्या अवशेषांचे व्यवस्थापन.",
    },
    "Grape___Healthy": {
        "crop": "Grape", "severity": "Low",
        "treatment": "No treatment needed.",
        "fertilizer": "Balanced vineyard nutrition program.",
        "prevention": "Routine pruning and canopy management.",
        "name_mr": "द्राक्ष - निरोगी",
        "treatment_mr": "कोणत्याही उपचाराची गरज नाही.",
        "fertilizer_mr": "संतुलित द्राक्षबाग पोषण कार्यक्रम पाळा.",
        "prevention_mr": "नियमित छाटणी आणि वेल व्यवस्थापन करा.",
    },
    "Grape___Black_Rot": {
        "crop": "Grape", "severity": "High",
        "treatment": "Apply myclobutanil or mancozeb fungicide starting at bud break.",
        "fertilizer": "Balanced fertilizer; avoid excess nitrogen.",
        "prevention": "Remove mummified berries, prune for airflow, sanitize tools.",
        "name_mr": "द्राक्ष - काळा कुज (ब्लॅक रॉट)",
        "treatment_mr": "कळी फुटल्यापासून मायक्लोब्युटानिल किंवा मॅन्कोझेब बुरशीनाशक फवारा.",
        "fertilizer_mr": "संतुलित खत वापरा; जास्त नत्र टाळा.",
        "prevention_mr": "वाळलेली फळे काढून टाका, हवा खेळती राहण्यासाठी छाटणी करा, अवजारे निर्जंतुक करा.",
    },
    "Apple___Healthy": {
        "crop": "Apple", "severity": "Low",
        "treatment": "No treatment needed.",
        "fertilizer": "Balanced orchard fertilization program.",
        "prevention": "Routine pruning and pest monitoring.",
        "name_mr": "सफरचंद - निरोगी",
        "treatment_mr": "कोणत्याही उपचाराची गरज नाही.",
        "fertilizer_mr": "संतुलित फळबाग खत कार्यक्रम पाळा.",
        "prevention_mr": "नियमित छाटणी आणि किड नियंत्रण करा.",
    },
    "Apple___Scab": {
        "crop": "Apple", "severity": "Medium",
        "treatment": "Apply captan or myclobutanil fungicide at green tip stage.",
        "fertilizer": "Balanced NPK; avoid excess nitrogen in spring.",
        "prevention": "Rake and destroy fallen leaves, prune for airflow.",
        "name_mr": "सफरचंद - खरूज (स्कॅब)",
        "treatment_mr": "हिरव्या टोकाच्या अवस्थेत कॅप्टन किंवा मायक्लोब्युटानिल बुरशीनाशक फवारा.",
        "fertilizer_mr": "संतुलित NPK खत; वसंत ऋतूत जास्त नत्र टाळा.",
        "prevention_mr": "गळलेली पाने गोळा करून नष्ट करा, हवा खेळती राहण्यासाठी छाटणी करा.",
    },
    "Apple___Black_Rot": {
        "crop": "Apple", "severity": "High",
        "treatment": "Prune out cankers, apply captan-based fungicide.",
        "fertilizer": "Balanced fertilization, avoid over-fertilizing with nitrogen.",
        "prevention": "Remove mummified fruit, sanitize pruning tools.",
        "name_mr": "सफरचंद - काळा कुज",
        "treatment_mr": "कँकर छाटून टाका, कॅप्टन-आधारित बुरशीनाशक फवारा.",
        "fertilizer_mr": "संतुलित खत द्या, जास्त नत्र देणे टाळा.",
        "prevention_mr": "वाळलेली फळे काढून टाका, छाटणीची अवजारे निर्जंतुक करा.",
    },
}
